# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 秋月春风的书房
subtitle: "拾光°"
description: ""
keywords:
author: 秋月春风
language: zh_CN
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://yukinoshitasherry.github.io
permalink: :slug/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# syntax_highlighter: highlight.js
highlight:
  enable: false # we will use the prism plugin instead
  # line_number: true
  # auto_detect: false
  # tab_replace: ''
  # wrap: true
  # hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

theme: typography

plugin:
  - hexo-generator-category-enhance
  - hexo-generator-feed
  - hexo-asset-image
  - hexo-prism-plugin
  - hexo-toc
# ... other plugins you'd like to enable

# Generate archive page
archive_generator:
  per_page: 0

# Generate categories index page and each category page
category_generator:
  per_page: 10
  enable_index_page: true

# Generate tags index page and each tag page
tag_generator:
  per_page: 10
  enable_index_page: true

# Generator atom feed for you website
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "

# For syntax highlighting
prism_plugin:
  mode: "preprocess"
  theme: "default"
  line_number: true

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""
# 添加博客分类
categories:
  - 上浙大
  - 学CS/SE
  - 学AI/DS
  - 学商科
  - 学英语
  - 学语言
  - 思万物
  - 吃什么
  - 喝咖啡
  - 拾光记
  - 进剧院
  - 观展览
  - 踏旅程
  - 读闲书
  - 析影视
  - 做运动


# 加密文章
security:
  enable_cross_domain: true
  enable_mixed_content: true

# Security
encrypt:
  enable: true
  default_template: |
    <style>
      /* 保持原有样式 */
      .hbe.hbe-container {
        width: 80%;
        max-width: 800px;
        margin: 60px auto;
        text-align: center;
      }
      
      /* 输入框 */
      .hbe.hbe-input-field {
        font-size: 12px !important;
        font-family: "Times New Roman", "楷体" !important;
        width: 50% !important;
        background: transparent !important;
        border: none !important;
        border-bottom: 1px solid #999 !important;
        outline: none !important;
        padding: 10px 0 !important;
        margin: 20px 0 !important;
        color: #bbb !important;
      }
      
      /* 提示文字 */
      .hbe.hbe-input-label-content {
        font-size: 10px !important;
        color: #999 !important;
        font-family: "Times New Roman", "楷体" !important;
      }
      
      /* 聚焦时的样式 */
      .hbe.hbe-input-field:focus {
        border-bottom: 1px solid #2e405b !important;
      }
      
      /* 确保加密内容容器不影响目录显示 */
      #hexo-blog-encrypt {
        position: relative;
        z-index: 1;
      }
      
      /* 调整目录容器样式 */
      .toc-container {
        display: block !important;
        opacity: 1 !important;
        visibility: visible !important;
        z-index: 2;
      }
    </style>



 

